### ISSUE TITLE
Deps outdated for newer Elixir/OTP environments

### ISSUE THREAD

**Issue by njwest** [kelseyleftwich/phoenix-liveview-hook-demo#1]
Thanks for this great example and walkthrough! I found your work here very helpful.

This example repo will throw a breaking error on **Elixir 1.12 compiled with Erlang/OTP 24** due to a breaking change to Erlang's `:crypto` module hmac functionality (Error/stacktrace below). 

**The solution** is to update all of the deps in `mix.exs`; apologies for not having the time to fork and pull request this fix myself

```elixir
[error] #PID<0.523.0> running DraggableWalkthruWeb.Endpoint (connection #PID<0.522.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function :crypto.hmac/3 is undefined or private
        (crypto 5.0.2) :crypto.hmac/3
        (plug_crypto 1.2.0) lib/plug/crypto/key_generator.ex:81: Plug.Crypto.KeyGenerator.generate/7
        (plug_crypto 1.2.0) lib/plug/crypto/key_generator.ex:67: Plug.Crypto.KeyGenerator.with_cache/3
        (plug_crypto 1.2.0) lib/plug/crypto/key_generator.ex:51: Plug.Crypto.KeyGenerator.generate/6
        (plug_crypto 1.2.0) lib/plug/crypto.ex:175: Plug.Crypto.sign/4
        (phoenix_live_view 0.13.0) lib/phoenix_live_view/static.ex:131: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.13.0) lib/phoenix_live_view/controller.ex:35: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.5.6) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (draggable_walkthru 0.1.0) lib/draggable_walkthru_web/endpoint.ex:1: DraggableWalkthruWeb.Endpoint.plug_builder_call/2
        (draggable_walkthru 0.1.0) lib/plug/debugger.ex:132: DraggableWalkthruWeb.Endpoint."call (overridable 3)"/2
        (draggable_walkthru 0.1.0) lib/draggable_walkthru_web/endpoint.ex:1: DraggableWalkthruWeb.Endpoint.call/2
        (phoenix 1.5.6) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.8.0) /phoenix-liveview-hook-demo/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.8.0) /phoenix-liveview-hook-demo/deps/cowboy/src/cowboy_stream_h.erl:300: :cowboy_stream_h.execute/3
        (cowboy 2.8.0) /phoenix-liveview-hook-demo/deps/cowboy/src/cowboy_stream_h.erl:291: :cowboy_stream_h.request_process/3
        (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

**Comment by davehorner** [comment]
@njwest thank you for the note.
```
mix deps.clean --all
mix deps.update --all
mix deps.get
mix compile
```
```
gh auth login
gh repo fork https://github.com/kelseyleftwich/phoenix-liveview-hook-demo.git
git remote add fork https://github.com/davehorner/phoenix-liveview-hook-demo.git
git commit -am "update deps"
git push fork main
gh pr create --base main --head davehorner:main --title "#1 update deps" --body "Deps outdated for newer Elixir/OTP environments"
```
https://github.com/kelseyleftwich/phoenix-liveview-hook-demo/pull/2

the update is not enough; i nvm use 16 and the projects works fine.  thanks @kelseyleftwich 
```
node:internal/crypto/hash:68
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (c:\working\elixir\phoenix-liveview-hook-demo\assets\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (c:\working\elixir\phoenix-liveview-hook-demo\assets\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (c:\working\elixir\phoenix-liveview-hook-demo\assets\node_modules\webpack\lib\NormalModule.js:471:10)
    at c:\working\elixir\phoenix-liveview-hook-demo\assets\node_modules\webpack\lib\NormalModule.js:503:5
    at c:\working\elixir\phoenix-liveview-hook-demo\assets\node_modules\webpack\lib\NormalModule.js:358:12
    at c:\working\elixir\phoenix-liveview-hook-demo\assets\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (c:\working\elixir\phoenix-liveview-hook-demo\assets\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (c:\working\elixir\phoenix-liveview-hook-demo\assets\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at c:\working\elixir\phoenix-liveview-hook-demo\assets\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at context.callback (c:\working\elixir\phoenix-liveview-hook-demo\assets\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at c:\working\elixir\phoenix-liveview-hook-demo\assets\node_modules\babel-loader\lib\index.js:44:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```
